//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoPoSim.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HoPoSim.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to navigate away from the settings page?.
        /// </summary>
        public static string ConfirmNavigateAwayFromSettingsMessage {
            get {
                return ResourceManager.GetString("ConfirmNavigateAwayFromSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmNavigateAwayFromSettingsTitle {
            get {
                return ResourceManager.GetString("ConfirmNavigateAwayFromSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei einer Netzwerkinstallation geben Sie hier bitte den Pfad, unter die Datenbank der Application zu finden ist.
        ///Ändern Sie diese Option nur, wenn Sie genau wissen, was Sie tun..
        /// </summary>
        public static string Einstellungen_DatabankPfad_ToolTip {
            get {
                return ResourceManager.GetString("Einstellungen_DatabankPfad_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie ein gültiges Datenbankverzeichnis ein .
        /// </summary>
        public static string Einstellungen_DatabaseDirectory_RequiredFailed {
            get {
                return ResourceManager.GetString("Einstellungen_DatabaseDirectory_RequiredFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie ein gültiges Verzeichnis ein.
        /// </summary>
        public static string Einstellungen_DocumentsDirectory_RequiredFailed {
            get {
                return ResourceManager.GetString("Einstellungen_DocumentsDirectory_RequiredFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be float.
        /// </summary>
        public static string IsFloatRuleValidationFailed {
            get {
                return ResourceManager.GetString("IsFloatRuleValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei &apos;{0}&apos; kann nicht hinzugefügt werden!
        ///Bitte stellen Sie sicher, dass das eingestellte Dokumentenverzeichnis nicht schreibgeschützt ist und versuchen bitte erneut..
        /// </summary>
        public static string Notification_DocumentCannotBeCopied {
            get {
                return ResourceManager.GetString("Notification_DocumentCannotBeCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Dokument kann nicht geöffnet werden!
        ///Bitte stellen Sie sicher, dass die Datei &apos;{0}&apos; existiert und zugreifbar ist, und versuchen bitte erneut..
        /// </summary>
        public static string Notification_DocumentCannotBeFound {
            get {
                return ResourceManager.GetString("Notification_DocumentCannotBeFound", resourceCulture);
            }
        }
    }
}
